# Sniperkit-Bot
# - Status: analyzed

project:
  name: "Gitor"
  state: "unstable"
  image: ""
  website: ""
  oneLiner: "CLI code syncing between repositories"
  description: |
    Mirror your repositories between Github, Gitlab or other platforms.
    Archive your projects, backup your dependencies or keep your forks up to date.
  version: "v0.0.0"
  mainLicense: "apache2"
  docsLicense: "CCBySa"

vision:
  type: "community"
  overview: |
    The project implements a simple mirroring implementation in pure Go.
  items:
    - "No reliance on non Go code/deps"
    - "Simple mirroring for now"
    - "Edgecases might not be added"
  concept: "Gitor wants to make a static binary git mirroring cli tool possible."

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/sniperkit/snk.fork.gitor/labels/starter%20issue"

emails:
  commercialSupport: "support@okkur.io"
  security: "security@okkur.io"
  coc: "coc@okkur.io"

copyright:
  year: "2017"

cla:
  copyrightHolder: "Michael Grosser"

maintainers:
  - name: "David Briesz"
    nick: "dbriesz"
  - name: "Michael Grosser"
    nick: "stp-ip"

repo:
  link: "https://github.com/sniperkit/snk.fork.gitor/"
  type: "Github"

badges:
  - image: "https://img.shields.io/badge/state-unstable-blue.svg"
    alt: "state"
  - image: "https://img.shields.io/github/release/sniperkit/snk.fork.gitor.svg"
    link: "https://github.com/sniperkit/snk.fork.gitor/releases"
    alt: "release"
  - image: "https://img.shields.io/github/license/sniperkit/snk.fork.gitor.svg"
    link: "LICENSE"
    alt: "license"
